from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

try:
    from scripts.a1_media_runtime_contracts import (
        OPTION_MEDIA_VARIANTS,
        TWO_CARD_ACTION_POSTERS,
        course_browser_media_usages,
    )
except ModuleNotFoundError:  # Direct `python scripts/...` execution.
    from a1_media_runtime_contracts import (
        OPTION_MEDIA_VARIANTS,
        TWO_CARD_ACTION_POSTERS,
        course_browser_media_usages,
    )
from lesson_asset_sync import copy_lesson_image_if_changed


ROOT = Path(__file__).resolve().parents[1]
BACKEND_ROOT = ROOT / "backend"
OUTPUT_ROOT = ROOT / "mobile" / "src" / "generated"
LESSON_IMAGE_ROOT = ROOT / "Lessons" / "Lesson1" / "images"
MOBILE_IMAGE_ROOT = ROOT / "mobile" / "assets" / "lesson-assets"
FRONTEND_IMAGE_ROOT = ROOT / "frontend" / "public" / "lesson-assets"
IMAGE_SOURCE_PATH = ROOT / "mobile" / "src" / "lessonImageSources.ts"
COURSE_MENU_IMAGE_NAMES = {
    "family_all_members.webp",
    "place_park.webp",
    "a1_ana.webp",
    "a1_home.webp",
    "a1_apple.webp",
    "a1_station.webp",
}

sys.path.insert(0, str(BACKEND_ROOT))

from app.data import LESSONS  # noqa: E402


def model_payload(model: object) -> dict[str, object]:
    if hasattr(model, "model_dump"):
        payload = model.model_dump(mode="json")  # type: ignore[no-any-return, union-attr]
    else:
        payload = json.loads(model.json())  # type: ignore[no-any-return, union-attr]
    for card in payload.get("cards", []):
        if card.get("spanish_translation") is None:
            card.pop("spanish_translation", None)
    return payload


def export_lesson(lesson_id: str) -> Path:
    lesson = LESSONS.get(lesson_id)
    if lesson is None:
        raise SystemExit(f"Unknown lesson: {lesson_id}")

    OUTPUT_ROOT.mkdir(parents=True, exist_ok=True)
    destination = OUTPUT_ROOT / f"{lesson_id}.json"
    destination.write_text(
        json.dumps(model_payload(lesson), ensure_ascii=True, indent=2) + "\n",
        encoding="utf-8",
    )
    return destination


def export_course(lesson_ids: list[str]) -> Path:
    destination = OUTPUT_ROOT / "a1-course.json"
    destination.write_text(
        json.dumps(
            [model_payload(LESSONS[lesson_id]) for lesson_id in lesson_ids],
            ensure_ascii=True,
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    return destination


def lesson_image_names() -> list[str]:
    names: set[str] = set(COURSE_MENU_IMAGE_NAMES)
    option_names: set[str] = set()
    for lesson in LESSONS.values():
        for card in lesson.cards:
            paths = [card.prompt_image_url, *(option.image_url for option in card.options)]
            for image_url in paths:
                clean_path = str(image_url or "").split("?", 1)[0].split("#", 1)[0]
                name = Path(clean_path).name
                if name.endswith(".webp"):
                    names.add(name)
            for option in card.options:
                clean_path = str(option.image_url or "").split("?", 1)[0].split("#", 1)[0]
                name = Path(clean_path).name
                if name.endswith(".webp"):
                    option_names.add(name)
    names.update(
        variant for source, variant in OPTION_MEDIA_VARIANTS.items() if source in option_names
    )
    names.update(TWO_CARD_ACTION_POSTERS.values())
    browser_lessons = [model_payload(lesson) for lesson in LESSONS.values()]
    names.update(
        usage["rendered_filename"]
        for usage in course_browser_media_usages(browser_lessons)
    )
    return sorted(names)


def export_lesson_images() -> int:
    names = lesson_image_names()
    missing = [name for name in names if not (LESSON_IMAGE_ROOT / name).is_file()]
    if missing:
        raise SystemExit(f"Missing canonical lesson images: {', '.join(missing)}")

    MOBILE_IMAGE_ROOT.mkdir(parents=True, exist_ok=True)
    FRONTEND_IMAGE_ROOT.mkdir(parents=True, exist_ok=True)
    for name in names:
        source = LESSON_IMAGE_ROOT / name
        copy_lesson_image_if_changed(source, MOBILE_IMAGE_ROOT / name)
        copy_lesson_image_if_changed(source, FRONTEND_IMAGE_ROOT / name)

    requires = "\n".join(
        f"  '{name}': require('../assets/lesson-assets/{name}')," for name in names
    )
    option_variants = "\n".join(
        f"  '{source}': '{variant}'," for source, variant in OPTION_MEDIA_VARIANTS.items()
    )
    IMAGE_SOURCE_PATH.write_text(
        "import type { ImageSourcePropType } from 'react-native';\n\n"
        "import { absoluteMediaUrl } from './config';\n\n"
        "// Generated by scripts/export_mobile_preview_lessons.py. Metro requires\n"
        "// literal require calls so every required A1 still travels with Preview OTA updates.\n"
        "const BUNDLED_LESSON_IMAGES: Record<string, ImageSourcePropType> = {\n"
        f"{requires}\n"
        "};\n\n"
        "const OPTION_MEDIA_VARIANTS: Record<string, string> = {\n"
        f"{option_variants}\n"
        "};\n\n"
        "function imageFilename(imageUrl: string): string {\n"
        "  const cleanPath = imageUrl.split(/[?#]/, 1)[0];\n"
        "  return cleanPath.slice(cleanPath.lastIndexOf('/') + 1);\n"
        "}\n\n"
        "export function lessonImageSource(imageUrl: string): ImageSourcePropType {\n"
        "  return BUNDLED_LESSON_IMAGES[imageFilename(imageUrl)] ?? { uri: absoluteMediaUrl(imageUrl) };\n"
        "}\n\n"
        "export function lessonOptionImageSource(imageUrl: string): ImageSourcePropType {\n"
        "  const filename = imageFilename(imageUrl);\n"
        "  const optionFilename = OPTION_MEDIA_VARIANTS[filename] ?? filename;\n"
        "  return BUNDLED_LESSON_IMAGES[optionFilename] ?? { uri: absoluteMediaUrl(imageUrl) };\n"
        "}\n",
        encoding="utf-8",
    )
    return len(names)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Export reviewed backend lessons for the Expo Preview app."
    )
    parser.add_argument(
        "--lesson-id",
        action="append",
        dest="lesson_ids",
        default=[],
        help="Lesson ID to export. May be supplied more than once.",
    )
    args = parser.parse_args()
    lesson_ids = args.lesson_ids or [lesson.id for lesson in LESSONS.values()]

    for lesson_id in lesson_ids:
        destination = export_lesson(lesson_id)
        print(destination.relative_to(ROOT))
    course_destination = export_course(lesson_ids)
    print(course_destination.relative_to(ROOT))
    image_count = export_lesson_images()
    print(f"Bundled {image_count} required A1 lesson images for Expo Preview.")


if __name__ == "__main__":
    main()
